function [para_id] = para_name_to_id(para_name)
%turns the name of a parameter into the id number required by the program
para_name = upper(para_name);
keys = {'CFD_LIMIT_LOW', 'CFD_LIMIT_HIGH', 'CFD_ZC_LEVEL', 'CFD_HOLDOFF', 'SYNC_ZC_LEVEL', 'SYNC_FREQ_DIV', 'SYNC_HOLDOFF', 'SYNC_THRESHOLD', 'TAC_RANGE', 'TAC_GAIN', 'TAC_OFFSET', 'TAC_LIMIT_LOW', 'TAC_LIMIT_HIGH', 'ADC_RESOLUTION', 'EXT_LATCH_DELAY', 'COLLECT_TIME', 'DISPLAY_TIME', 'REPEAT_TIME', 'STOP_ON_TIME', 'STOP_ON_OVFL', 'DITHER_RANGE', 'COUNT_INCR', 'MEM_BANK', 'DEAD_TIME_COMP', 'SCAN_CONTROL', 'ROUTING_MODE', 'TAC_ENABLE_HOLD', 'MODE', 'SCAN_SIZE_X', 'SCAN_SIZE_Y', 'SCAN_ROUT_X', 'SCAN_ROUT_Y', 'SCAN_POLARITY', 'SCAN_FLYBACK', 'SCAN_BORDERS', 'PIXEL_TIME', 'PIXEL_CLOCK', 'LINE_COMPRESSION', 'TRIGGER', 'EXT_PIXCLK_DIV', 'RATE_COUNT_TIME', 'MACRO_TIME_CLK', 'ADD_SELECT', 'ADC_ZOOM', 'XY_GAIN', 'IMG_SIZE_X', 'IMG_SIZE_Y', 'IMG_ROUT_X', 'IMG_ROUT_Y', 'MASTER_CLOCK', 'ADC_SAMPLE_DELAY', 'DETECTOR_TYPE', 'X_AXIS_TYPE', 'CHAN_ENABLE', 'CHAN_SLOPE', 'CHAN_SPEC_NO'};
vals = [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55];
para_map = containers.Map(keys, vals);
para_id = para_map(para_name);
end

